### ISSUE TITLE
Create tests for options.js

### ISSUE THREAD

**Issue by rclee91** [aserputov/QckStaticSiteGenerator#15]
I checked out your code and its missing tests for `options.js`.
I'd like to create tests for it.
Please assign. Many thanks.

**Comment by aserputov** [comment]
@rclee91 if you will have any questions just let me know.

**Comment by rclee91** [comment]
![image](https://user-images.githubusercontent.com/32626950/142581427-691c74ef-396c-4a74-940e-be88e23f4617.png)
Your `husky precommit` is causing problems. 
What exactly does it want?
