### ISSUE TITLE
Adding more Unit tests to the tool

### ISSUE THREAD

**Issue by abatomunkuev** [aserputov/QckStaticSiteGenerator#17]
Hello @aserputov! 

I would like to add more unit tests to your tool. I am thinking about testing Command Line Parser. Specifically, I would like to add a test case which checks the performance of the tool if we provide a json object as a config file.

**Comment by aserputov** [comment]
Hello ... @abatomunkuev

**Comment by aserputov** [comment]
Go ahead

**Comment by aserputov** [comment]
@abatomunkuev please don't forget to update README.md/ all others .md files.

**Comment by aserputov** [comment]
Thank you !
